# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171125_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
