# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171125_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_source', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='file_source',
            new_name='hash',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='file_source',
        ),
        migrations.AddField(
            model_name='lecture',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
